### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Kevinlyk2000** [chloeouyang/coursehunter#2]
Content : (1). I think adding Chinese original names for the Classical Gardens will be better for people who speak Chinese to quickly relate and understand. (2). I look forward to seeing more Classical Gardens, such as 环秀山庄 and 沧浪亭 be added to the list. 

Technical : (1). Using external css files can make each part of the project easier to read in my opinion (2). `><img
              src="images/wangshi.jpg"
              alt="wangshi"
              title="Click me!"
              width="300"
              height="230"
          /></a>`
Title does not correspond to the name of the gardens.

**Comment by chloeouyang** [comment]
I really appreciate it. Thank you!
