### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by ssetty767** [chloeouyang/coursehunter#3]
Content: 
1. Could be interesting to add a map so that people could see the location within the website. 
2. Homepage can use a bit more introduction to let people know what the website is about.

Technical:
1. For the gardens, the section where you list out info, it could be nice to put that info in a table so that it's a bit cleaner.
2. For the text sections that describe the gardens, you could have it wrap under the picture as well so that people don't have to scroll down as much. It'll be a bit more centered too.

**Comment by chloeouyang** [comment]
I really appreciate it. Thank you!
